FROM node:22-bookworm-slim AS devbase

WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable \
    && corepack prepare pnpm@10.15.0 --activate \
    && pnpm config set store-dir /pnpm/store

COPY package.json pnpm-lock.yaml ./
COPY .npmrc ./

RUN pnpm fetch

RUN pnpm install --offline --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["pnpm", "dev", "--host", "0.0.0.0"]